WeatherLogSystem2: Time.h File Reference
Time.h File Reference
Time class for storing 24 hour time Splits in hour and minute before storing as unsigned int Expects only 24 hour time.
#include <iostream>
Classes
class Time
Functions
bool operator< (const Time &lt, const Time &rt)
Operator overload of < comparison. Compares hour and minute.
bool operator> (const Time &lt, const Time &rt)
Operator overload of > comparison. Compares hour and minute.
bool operator== (const Time &lt, const Time &rt)
Overloaded operator for ==. Equal Time.
Detailed Description
Time class for storing 24 hour time Splits in hour and minute before storing as unsigned int Expects only 24 hour time.
Author
Khon Min Thite
Version
0.1
Date
18-02-2024
Version
0.2
Date
5-3-2024 Added Operator overload > for BST insertion Added Operator overload < for BST insertion Added Operator overload == for BST insertion
Definition in file Time.h.
Function Documentation
operator<()
bool operator< (const Time & lt, const Time & rt)
Operator overload of < comparison. Compares hour and minute.
Parameters
lt - The Time object on the left side of comparison
rt - The Time object on the right side of comparison
Returns
true - If lt is less than rt
false - If lt is more than rt
Definition at line 62 of file Time.cpp.
{
    if(lt.GetHour() != rt.GetHour())
    {
        return lt.GetHour() < rt.GetHour();
    }
    return lt.GetMinute() < rt.GetMinute();
}
References Time::GetHour(), and Time::GetMinute().
Referenced by operator<().
operator==()
bool operator== (const Time & lt, const Time & rt)
Overloaded operator for ==. Equal Time.
Parameters
lt - The time object on the left
rt - The time object on the right
Returns
true - if lt is equal to rt
false - if lt is not equal to rt
Definition at line 80 of file Time.cpp.
{
    return lt.GetHour() == rt.GetHour() && lt.GetMinute() == rt.GetMinute();
}
References Time::GetHour(), and Time::GetMinute().
Referenced by operator==().
operator>()
bool operator> (const Time & lt, const Time & rt)
Operator overload of > comparison. Compares hour and minute.
Parameters
lt - The Time object on the left side of comparison
rt - The Time object on the right side of comparison
Returns
true - If lt is more than rt
false - If lt is less than rt
Definition at line 71 of file Time.cpp.
{
    if(lt.GetHour() != rt.GetHour())
    {
        return lt.GetHour() > rt.GetHour();
    }
    return lt.GetMinute() > rt.GetMinute();
}
References Time::GetHour(), and Time::GetMinute().
Referenced by operator>().