WeatherLogSystem2: WeatherTest.cpp File Reference
WeatherTest.cpp File Reference
Unit Test for Weather.
#include "Weather.h"
#include <iostream>
Functions
int main ()
Detailed Description
Unit Test for Weather.
Author
Khon Min Thite
Version
0.1
Date
29-2-2024
Version
0.2
Date
Added testing for < operator overload function Added testing for > operator overload function
Definition in file WeatherTest.cpp.
Function Documentation
main()
int main ()
Definition at line 19 of file WeatherTest.cpp.
{
    //Check that constructor correctly initialize the data and all getters can retrieve the data
    cout << " Check constructor" << endl;
    Weather testWeather1;
    cout << " Date: " << testWeather1.GetDate().DisplayFullDate() << endl;
    cout << " Time: " << testWeather1.GetTime().Display24HTime() << endl;
    cout << " Wind Speed: " << testWeather1.GetWindSpeed() << endl;
    cout << " Solar Radiation" << testWeather1.GetSolarRadiation() << endl;
    cout << " Air Temperature: " << testWeather1.GetAirTemperature() << endl;
    cout << endl;
    //Check that setters are working correctly
    Weather testWeather2;
    cout << " Test Setters " << endl;
    cout << "--------------" << endl;
    //Check that Date setter are working correctly
    cout << " Test Date setter" << endl;
    Date testDate(16,3,2016);
    testWeather2.SetDate(testDate);
    cout << " Date: " << testWeather2.GetDate().DisplayFullDate() << endl;
    cout << endl;
    //Check that Time setter are working correctly
    cout << " Test Time setter" << endl;
    Time testTime(9,15);
    testWeather2.SetTime(testTime);
    cout << " Time: " << testWeather2.GetTime().Display24HTime() << endl;
    cout << endl;
    //Check that Wind Speed setter are working correctly
    cout << " Test Wind Speed Setter" << endl;
    testWeather2.SetWindSpeed(11.1);
    cout << " Wind Speed: " << testWeather2.GetWindSpeed() << endl;
    cout << endl;
    //Check that Solar Radiation setter are working correctly
    cout << " Test Solar radiation Setter" << endl;
    testWeather2.SetSolarRadiation(23.15);
    cout << " Solar Radiation: " << testWeather2.GetSolarRadiation() << endl;
    cout << endl;
    //Check that Air Temperature setter are working correctly
    cout << " Test Air temp setter" << endl;
    testWeather2.SetAirTemp(78.25);
    cout << " Air Temperature: " << testWeather2.GetAirTemperature() << endl;
    cout << endl;
    //Check that < operator can correctly compare the time of weather object
    cout << " Test < operator" << endl;
    cout << " Time of weather 1: " << testWeather1.GetTime().Display24HTime() << endl;
    cout << " Time of weather 2: " << testWeather2.GetTime().Display24HTime() << endl;
    cout << " Compare weather 1 < weather 2: " << (testWeather1 < testWeather2) << endl;
    cout << endl;
    //Check that > operator can correctly compare the time of weather object
    cout << " Test > operator" << endl;
    cout << " Time of weather 1: " << testWeather1.GetTime().Display24HTime() << endl;
    cout << " Time of weather 2: " << testWeather2.GetTime().Display24HTime() << endl;
    cout << " Compare weather 1 > weather 2: " << (testWeather1 > testWeather2) << endl;
    cout << endl;
    //Check that == operator can correctly equate the time of weather object
    cout << " Test == operator" << endl;
    cout << " Time of weather 1: " << testWeather1.GetTime().Display24HTime() << endl;
    cout << " Time of weather 2: " << testWeather2.GetTime().Display24HTime() << endl;
    cout << " Chack weather 1 == weather 2: " << (testWeather1 == testWeather2) << endl;
    cout << endl;
    return 0;
}
References Date::Date(), Weather::SetAirTemp(), Weather::SetDate(), Weather::SetSolarRadiation(), Weather::SetTime(), Weather::SetWindSpeed(), and Time::Time().