WeatherLogSystem2: Weather.cpp File Reference
Weather.cpp File Reference
.ccp for Weather.h
#include "Weather.h"
Functions
bool operator< (const Weather &lw, const Weather &rw)
Operator overload of < comparison. Compares Weather.
bool operator> (const Weather &lw, const Weather &rw)
Operator overload of > comparison. Compares Weather.
bool operator== (const Weather &lw, const Weather &rw)
Operator overload of ==. Equate Weather.
Detailed Description
.ccp for Weather.h
Author
Version
0.1
Date
2022-02-27
Definition in file Weather.cpp.
Function Documentation
operator<()
bool operator< (const Weather & lw, const Weather & rw)
Operator overload of < comparison. Compares Weather.
Parameters
lw - The Weather object on the left of comparison
rw - The Weather object on the right of comparison
Returns
true - If lw is less than rw
false - If lw is more than rw
Definition at line 75 of file Weather.cpp.
{
    return lw.GetTime() < rw.GetTime();
}
References Weather::GetTime(), and operator<().
operator==()
bool operator== (const Weather & lw, const Weather & rw)
Operator overload of ==. Equate Weather.
Parameters
lw - The Weather object on the left of comparison
rw - The Weather object on the right of comparison
Returns
true - If lw is equal to rw
false - If lw is not equal to rw
Definition at line 85 of file Weather.cpp.
{
    return lw.GetTime() == rw.GetTime();
}
References Weather::GetTime(), and operator==().
operator>()
bool operator> (const Weather & lw, const Weather & rw)
Operator overload of > comparison. Compares Weather.
Parameters
lw - The Weather object on the left of comparison
rw - The Weather object on the right of comparison
Returns
true - If lw is more than rw
false - If lw is less than rw
Definition at line 80 of file Weather.cpp.
{
    return lw.GetTime() > rw.GetTime();
}
References Weather::GetTime(), and operator>().