WeatherLogSystem2: BstWeatherHelper Class Reference
BstWeatherHelper Class Reference
#include <BstWeatherHelper.h>
Static Public Member Functions
static float GetWeatherWindSpeed (Weather &weather)
Get the Weather object's Wind Speed.
static float GetWeatherAirTemp (Weather &weather)
Get the Weather object's Air Temp.
static float GetWeatherSolarRad (Weather &weather)
Get the Weather object's Solar Rad.
Detailed Description
Definition at line 16 of file BstWeatherHelper.h.
Member Function Documentation
GetWeatherAirTemp()
float BstWeatherHelper::GetWeatherAirTemp (Weather & weather) static
Get the Weather object's Air Temp.
Parameters
weather - A weather object
Returns
float - the value of air temperature of weather
Definition at line 18 of file BstWeatherHelper.cpp.
{
    return weather.GetAirTemperature();
}
References Weather::GetAirTemperature().
GetWeatherSolarRad()
float BstWeatherHelper::GetWeatherSolarRad (Weather & weather) static
Get the Weather object's Solar Rad.
Parameters
weather - A weather object
Returns
float - the value of solar radiation of weather
Definition at line 23 of file BstWeatherHelper.cpp.
{
    return weather.GetSolarRadiation();
}
References Weather::GetSolarRadiation().
GetWeatherWindSpeed()
float BstWeatherHelper::GetWeatherWindSpeed (Weather & weather) static
Get the Weather object's Wind Speed.
Parameters
weather - A weather object
Returns
float - the value of wind speed of weather
Definition at line 13 of file BstWeatherHelper.cpp.
{
    return weather.GetWindSpeed();
}
References Weather::GetWindSpeed().
The documentation for this class was generated from the following files:
BstWeatherHelper.h
BstWeatherHelper.cpp