WeatherLogSystem2: Weather Class Reference
Weather Class Reference
#include <Weather.h>
Public Member Functions
Weather ()
Construct a new Weather object.
~Weather ()
Destroy the Weather object.
const Date & GetDate () const
Get m_date.
const Time & GetTime () const
Get m_time.
float GetWindSpeed () const
Get m_windSpeed.
float GetSolarRadiation () const
Get m_solarRad.
float GetAirTemperature () const
Get m_airTemp.
void SetDate (const Date &date)
Set m_date.
void SetTime (const Time &time)
Set m_time.
void SetWindSpeed (const float windSpeed)
Set m_windSpeed.
void SetSolarRadiation (const float solar)
Set m_solarRad.
void SetAirTemp (const float temp)
Set m_airTemp.
Private Attributes
Date m_date
Time m_time
float m_windSpeed
float m_solarRad
float m_airTemp
Detailed Description
Definition at line 24 of file Weather.h.
Constructor & Destructor Documentation
Weather()
Weather::Weather ()
Construct a new Weather object.
Definition at line 13 of file Weather.cpp.
{
    //Sets to -1
    m_windSpeed = 0.0;
    m_solarRad = 0.0;
    m_airTemp = 0.0;
}
References m_airTemp, m_solarRad, and m_windSpeed.
~Weather()
Weather::~Weather ()
Destroy the Weather object.
Definition at line 21 of file Weather.cpp.
{}
Member Function Documentation
GetAirTemperature()
float Weather::GetAirTemperature () const
Get m_airTemp.
Returns
float - Ambient Air Temperature
Definition at line 44 of file Weather.cpp.
{
    return m_airTemp;
}
References m_airTemp.
Referenced by BstWeatherHelper::GetWeatherAirTemp().
GetDate()
const Date & Weather::GetDate () const
Get m_date.
Returns
const Date& - Date object
Definition at line 24 of file Weather.cpp.
{
    return m_date;
}
References m_date.
Referenced by Logic::InsertWeatherToMap().
GetSolarRadiation()
float Weather::GetSolarRadiation () const
Get m_solarRad.
Returns
float - Solar Radiation
Definition at line 39 of file Weather.cpp.
{
    return m_solarRad;
}
References m_solarRad.
Referenced by BstWeatherHelper::GetWeatherSolarRad().
GetTime()
const Time & Weather::GetTime () const
Get m_time.
Returns
const Time& -Time Object
Definition at line 29 of file Weather.cpp.
{
    return m_time;
}
References m_time.
Referenced by operator<(), operator==(), and operator>().
GetWindSpeed()
float Weather::GetWindSpeed () const
Get m_windSpeed.
Returns
float - Wind Speed
Definition at line 34 of file Weather.cpp.
{
    return m_windSpeed;
}
References m_windSpeed.
Referenced by BstWeatherHelper::GetWeatherWindSpeed().
SetAirTemp()
void Weather::SetAirTemp (const float temp)
Set m_airTemp.
Parameters
temp - Ambient Air Temperature
Definition at line 70 of file Weather.cpp.
{
    m_airTemp = temp;
}
References m_airTemp.
Referenced by main().
SetDate()
void Weather::SetDate (const Date & date)
Set m_date.
Parameters
date - Date object
Definition at line 50 of file Weather.cpp.
{
    m_date = date;
}
References m_date.
Referenced by main().
SetSolarRadiation()
void Weather::SetSolarRadiation (const float solar)
Set m_solarRad.
Parameters
solar - Solar Radiation
Definition at line 65 of file Weather.cpp.
{
    m_solarRad = solar;
}
References m_solarRad.
Referenced by main().
SetTime()
void Weather::SetTime (const Time & time)
Set m_time.
Parameters
time - Time object
Definition at line 55 of file Weather.cpp.
{
    m_time = time;
}
References m_time.
Referenced by main().
SetWindSpeed()
void Weather::SetWindSpeed (const float windSpeed)
Set m_windSpeed.
Parameters
windSpeed - wind speed
Definition at line 60 of file Weather.cpp.
{
    m_windSpeed = windSpeed;
}
References m_windSpeed.
Referenced by main().
Member Data Documentation
m_airTemp
float Weather::m_airTemp private
Definition at line 120 of file Weather.h.
Referenced by GetAirTemperature(), SetAirTemp(), and Weather().
m_date
Date Weather::m_date private
Definition at line 112 of file Weather.h.
Referenced by GetDate(), and SetDate().
m_solarRad
float Weather::m_solarRad private
Definition at line 118 of file Weather.h.
Referenced by GetSolarRadiation(), SetSolarRadiation(), and Weather().
m_time
Time Weather::m_time private
Definition at line 114 of file Weather.h.
Referenced by GetTime(), and SetTime().
m_windSpeed
float Weather::m_windSpeed private
Definition at line 116 of file Weather.h.
Referenced by GetWindSpeed(), SetWindSpeed(), and Weather().
The documentation for this class was generated from the following files:
Weather.h
Weather.cpp