WeatherLogSystem2: Logic Class Reference
Logic Class Reference
A class that handles loading, processing, and analyzing weather data.
#include <Logic.h>
Public Member Functions
void LoadMultiDataFileCSV (ifstream &inputFile, map< int, map< int, map< int, Bst< Weather > > > > &windLog)
Reads the input file line by line for filename pass to LoadDataFileCSV function to read and load data into the wind log.
bool LoadDataFileCSV (ifstream &inputFile, map< int, map< int, map< int, Bst< Weather > > > > &windLog)
Load the data of an input data file and store it in a maps of binary search tree of weather.
void InsertWeatherToMap (map< int, map< int, map< int, Bst< Weather > > > > &windLog, Weather &tempLog)
Inserts tempLog into wind log.
string RemoveLeadingZeros (string input)
Removes leading 0 s from a given string.
float AverageWindSpeedMonth (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year)
Search and Calculates the average wind speed of a month when given the month and year to search for.
float StandardDeviationWindSpeed (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year)
Calculates the standard deviation of wind speed for a specified month and year.
float StandardDeviationAirTemperature (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year)
Calculates the standard deviation of air temperature for a specified month and year.
float AverageAirTemperatureMonth (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year)
Search and Calculates the average air temperature of a month when given the month and year to search for.
float SumSolarRadiationMonth (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year)
Search and Calculates the total solar radiation of a month when given the month and year to search for.
string IntMonthToString (const int &month)
Converts a given integer month to string month.
float ConvertWindMStoKMH (const float &windSpeed)
Converts wind speed m/s to km/h.
float ConvertSolarRadiationWMtoKWH (const float &radiation)
Converts solar radiation from W per 10 min to kWh.
void WriteAppendFile (const string &fileName, const string &output)
Create/Appends a given string into "WindTempSolar.csv".
float calculateSPCC (const Vector< float > &x, const Vector< float > &y)
Calculates Sample Pearson Correlation Coefficient (SPCC) between two vectors.
void extractMonthData (const map< int, map< int, map< int, Bst< Weather > > > > &windLog, const int month, const int year, Vector< float > &windSpeeds, Vector< float > &airTemps, Vector< float > &solarRads)
Extracts data for a specified month and year from the wind log.
Detailed Description
A class that handles loading, processing, and analyzing weather data.
This class provides functionality for loading weather data from CSV files, inserting weather data into a binary search tree (BST) structure, and performing various calculations and conversions on the data.
Definition at line 47 of file Logic.h.
Member Function Documentation
AverageAirTemperatureMonth()
float Logic::AverageAirTemperatureMonth (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year)
Search and Calculates the average air temperature of a month when given the month and year to search for.
Parameters
array - The maps of binary search tree of weather to search in
month - The month to search for
year - The year to search for
Returns
float - The average air temperature of a month
Definition at line 345 of file Logic.cpp.
{
    BstWeatherHelper BWH;
    float totalAirTemperature = 0.0;
    int count = 0;
    //Check if data of that year exist
    if(windLog.count(year) > 0)
    {
        //Check if data of that year and month exist
        if(windLog.at(year).count(month) > 0)
        {
            //Loops through the month map for each day
            //Get BST <Weather> of each day and get count and total airTemp of each day
            map<int, Bst<Weather>>::const_iterator it;
            for (it = windLog.at(year).at(month).begin(); it != windLog.at(year).at(month).end(); ++it)
            {
                totalAirTemperature += it->second.GetSumValueFloat(&BWH.GetWeatherAirTemp);
                count += it->second.TreeNodeCount();
            }
        }
        else //No data of that date exist
        {
            return -1;
        }
    }
    else //No data of that date exist
    {
        return -1;
    }
    return totalAirTemperature/count;
}
AverageWindSpeedMonth()
float Logic::AverageWindSpeedMonth (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year)
Search and Calculates the average wind speed of a month when given the month and year to search for.
Parameters
array - The maps of binary search tree of weather to search in
month - The month to search for
year - The year to search for
Returns
float - The average wind speed of a month
Definition at line 262 of file Logic.cpp.
{
    BstWeatherHelper BWH;
    float totalWindSpeed = 0.0;
    int count = 0;
    //Check if data of that year exist
    if(windLog.count(year) > 0)
    {
        //Check if data of that year and month exist
        if(windLog.at(year).count(month) > 0)
        {
            //Loops through the month map for each day
            //Get BST <Weather> of each day and get count and total wind speed of each day
            map<int, Bst<Weather>>::const_iterator it;
            for (it = windLog.at(year).at(month).begin(); it != windLog.at(year).at(month).end(); ++it)
            {
                totalWindSpeed += it->second.GetSumValueFloat(&BWH.GetWeatherWindSpeed);
                count += it->second.TreeNodeCount();
            }
        }
        else //No data of that date exist
        {
            return -1;
        }
    }
    else //No data of that date exist
    {
        return -1;
    }
    return totalWindSpeed/count;
}
calculateSPCC()
float Logic::calculateSPCC (const Vector< float > & x, const Vector< float > & y)
Calculates Sample Pearson Correlation Coefficient (SPCC) between two vectors.
This method calculates Sample Pearson Correlation Coefficient between two vectors of floating-point numbers.
Parameters
x - The first vector of floating-point numbers.
y - The second vector of floating-point numbers.
Returns
Sample Pearson Correlation Coefficient between the two vectors.
Definition at line 531 of file Logic.cpp.
{
    if (x.size() != y.size())
    {
        std::cerr << "Error: Vectors must be of the same size." << std::endl;
        return std::numeric_limits<float>::quiet_NaN();
    }
    float sumX = 0.0, sumY = 0.0;
    for (unsigned i = 0; i < x.size(); ++i)
    {
        sumX += x[i];
        sumY += y[i];
    }
    float meanX = sumX / x.size();
    float meanY = sumY / y.size();
    float sumNumerator = 0.0;
    float sumDenominatorX = 0.0;
    float sumDenominatorY = 0.0;
    for (unsigned i = 0; i < x.size(); ++i)
    {
        sumNumerator += (x[i] - meanX) * (y[i] - meanY);
        sumDenominatorX += (x[i] - meanX) * (x[i] - meanX);
        sumDenominatorY += (y[i] - meanY) * (y[i] - meanY);
    }
    float denominator = std::sqrt(sumDenominatorX * sumDenominatorY);
    if (denominator == 0)
    {
        cerr << "Error: Division by zero." << endl;
        return numeric_limits<float>::quiet_NaN();
    }
    return sumNumerator / denominator;
}
ConvertSolarRadiationWMtoKWH()
float Logic::ConvertSolarRadiationWMtoKWH (const float & radiation)
Converts solar radiation from W per 10 min to kWh.
Parameters
radiation - Radiation in W per 10 min
Returns
float - Radiation in kWh
Definition at line 514 of file Logic.cpp.
{
    if (radiation > 0)
    {
        return (radiation/6) /  1000;
    }
    return 0;
}
Referenced by FunctionHelper::FindSumSolarRadMonth(), and FunctionHelper::OutputFileAverageWindTempSolarMonth().
ConvertWindMStoKMH()
float Logic::ConvertWindMStoKMH (const float & windSpeed)
Converts wind speed m/s to km/h.
Parameters
windSpeed - wind speed in m/s
Returns
float - wind speed in km/h
Definition at line 505 of file Logic.cpp.
{
    if(windSpeed < 0)
    {
        return 0;
    }
    return windSpeed * 3.6;
}
Referenced by FunctionHelper::FindAverageWindSpeedAndStandardDeviationMonth(), and FunctionHelper::OutputFileAverageWindTempSolarMonth().
extractMonthData()
void Logic::extractMonthData (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year, Vector< float > & windSpeeds, Vector< float > & airTemps, Vector< float > & solarRads)
Extracts data for a specified month and year from the wind log.
This method extracts wind speeds, air temperatures, and solar radiation data for a specified month and year from the wind log.
Parameters
windLog - The map of BSTs containing the weather data.
month - The month to extract data for.
year - The year to extract data for.
windSpeeds - A vector to store the extracted wind speeds.
airTemps - A vector to store the extracted air temperatures.
solarRads - A vector to store the extracted solar radiation data.
Definition at line 569 of file Logic.cpp.
{
    // Check if the year exists in the map
    auto yearIt = windLog.find(year);
    if (yearIt != windLog.end())
    {
        // Check if the month exists for the given year
        auto monthIt = yearIt->second.find(month);
        if (monthIt != yearIt->second.end())
        {
            // Iterate through each day of the month
            for (const auto& dayEntry : monthIt->second)
            {
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                    {
                        windSpeeds.push_back(w.GetWindSpeed());
                        return w.GetWindSpeed();
                    });
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                    {
                        airTemps.push_back(w.GetAirTemperature());
                        return w.GetAirTemperature();
                    });
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                    {
                        solarRads.push_back(w.GetSolarRadiation());
                        return w.GetSolarRadiation();
                    });
            }
        }
    }
}
InsertWeatherToMap()
void Logic::InsertWeatherToMap (map< int, map< int, map< int, Bst< Weather > > > > & windLog, Weather & tempLog)
Inserts tempLog into wind log.
Parameters
windLog - The maps of binary search tree of weather
tempLog - The weather object to be inserted into windLog
Definition at line 208 of file Logic.cpp.
{
    int logYear = tempLog.GetDate().GetYear();
    int logMonth = tempLog.GetDate().GetMonth();
    int logDay = tempLog.GetDate().GetDay();
    // Check if year exists in windLog
    if(windLog.find(logYear) == windLog.end())
    {
        // Year does not exist, create new maps for month and day
        map<int, map<int, Bst<Weather>>> month;
        map<int, Bst<Weather>> day;
        Bst<Weather> tempBst;
        tempBst.Insert(tempLog);
        day[logDay] = tempBst;
        month[logMonth] = day;
        windLog[logYear] = month;
    }
    else
    {
        // Year exists, check if month exists
        if(windLog[logYear].find(logMonth) == windLog[logYear].end())
        {
            // Month does not exist, create new map for day
            map<int, Bst<Weather>> day;
            Bst<Weather> tempBst;
            tempBst.Insert(tempLog);
            day[logDay] = tempBst;
            windLog[logYear][logMonth] = day;
        }
        else
        {
            // Month exists, check if day exists
            if(windLog[logYear][logMonth].find(logDay) == windLog[logYear][logMonth].end())
            {
                // Day does not exist, create new BST
                Bst<Weather> tempBst;
                tempBst.Insert(tempLog);
                windLog[logYear][logMonth][logDay] = tempBst;
            }
            else
            {
                // Day exists, insert directly
                windLog[logYear][logMonth][logDay].Insert(tempLog);
            }
        }
    }
}
References Weather::GetDate(), Date::GetDay(), Date::GetMonth(), and Date::GetYear().
IntMonthToString()
string Logic::IntMonthToString (const int & month)
Converts a given integer month to string month.
Parameters
month - A month in integer
Returns
string - A month in string
Definition at line 471 of file Logic.cpp.
{
    switch (month)
    {
    case 1:
        return "January";
    case 2:
        return "February";
    case 3:
        return "March";
    case 4:
        return "April";
    case 5:
        return "May";
    case 6:
        return "June";
    case 7:
        return "July";
    case 8:
        return "August";
    case 9:
        return "September";
    case 10:
        return "October";
    case 11:
        return "November";
    case 12:
        return "December";
    default:
        cout << endl << "Error converting int month to string" << endl;
        return "ERROR";
    }
}
LoadDataFileCSV()
bool Logic::LoadDataFileCSV (ifstream & inputFile, map< int, map< int, map< int, Bst< Weather > > > > & windLog)
Load the data of an input data file and store it in a maps of binary search tree of weather.
Parameters
inputFile - The input file
WindLog - The maps of binary search tree of weather
Returns
true - Load successful
false - Load unsuccessful
Definition at line 53 of file Logic.cpp.
{
    unsigned int recordCount = 0;
    Validator validateHelp;
    string line, column;
    istringstream row, dateTime, date, time;
    string dateField, timeField;
    string day, month, year;
    string hour, minute;
    Date tempDate;
    Time tempTime;
    Weather tempLog;
    bool re = true;
    // Get and ignore CSV header
    getline(inputFile, line);
    int columnIndices[4] = {-1, -1, -1, -1};
    istringstream headerStream(line);
    string columnName;
    int columnIndex = 0;
    while (getline(headerStream, columnName, ','))
    {
        if (columnName == "WAST") columnIndices[0] = columnIndex;
        else if (columnName == "S") columnIndices[1] = columnIndex;
        else if (columnName == "SR") columnIndices[2] = columnIndex;
        else if (columnName == "T") columnIndices[3] = columnIndex;
        columnIndex++;
    }
    // Loops for each row of record in file
    while (getline(inputFile, line))
    {
        if (line.find_first_not_of(',') == std::string::npos)
        {
            // Handle the line of commas here
            cout << "Warning: Line of commas detected at row " << recordCount + 2 << endl;
            continue;
        }
        if (line != "")
        {
            row.str(line);
            row.clear(); // Clear the stream flags
            string WAST, S, SR, T;
            int index = 0;
            while (getline(row, column, ','))
            {
                if (index == columnIndices[0]) WAST = column;
                else if (index == columnIndices[1]) S = column;
                else if (index == columnIndices[2]) SR = column;
                else if (index == columnIndices[3]) T = column;
                index++;
            }
            // Process WAST column to extract date and time
            dateTime.str(WAST);
            getline(dateTime, dateField, ' ');    // Date part of WAST
            getline(dateTime, timeField, ' ');    // Time part of WAST
            dateTime.clear();
            // Split Date into day, month, and year
            date.str(dateField);
            getline(date, day, '/');    // Day part of date
            getline(date, month, '/'); // Month part of date
            getline(date, year, '/');   // Year part of date
            date.clear();
            // Remove leading zeros and validate date
            day = RemoveLeadingZeros(day);
            month = RemoveLeadingZeros(month);
            year = RemoveLeadingZeros(year);
            if (!validateHelp.IsValidDate(stoi(day), stoi(month), stoi(year)))
            {
                cout << "Error: Invalid date(WAST) detected at row " << recordCount + 2 << endl;
                re = false;
            }
            else
            {
                tempDate.SetDay(stoi(day));
                tempDate.SetMonth(stoi(month));
                tempDate.SetYear(stoi(year));
                tempLog.SetDate(tempDate);
            }
            // Split Time into hour and minute
            time.str(timeField);
            getline(time, hour, ':');   // Hour part of time
            getline(time, minute, ':'); // Minute part of time
            time.clear();
            // Remove leading zeros and validate time
            hour = RemoveLeadingZeros(hour);
            minute = RemoveLeadingZeros(minute);
            if (!validateHelp.IsValid24HourTime(stoi(hour), stoi(minute)))
            {
                cout << "Error: Invalid time(WAST) detected at row: " << recordCount + 2 << endl;
                re = false;
            }
            else
            {
                tempTime.SetHour(stoi(hour));
                tempTime.SetMinute(stoi(minute));
                tempLog.SetTime(tempTime);
            }
            if (validateHelp.IsNumber(S))
            {
                tempLog.SetWindSpeed(stof(S));
            }
            else
            {
                cout << "Error: Invalid Wind Speed(S) detected at row: " << recordCount + 2 << endl;
                re = false;
            }
            if (validateHelp.IsNumber(SR))
            {
                tempLog.SetSolarRadiation(stof(SR));
            }
            else
            {
                cout << "Error: Invalid Solar Radiation(SR) detected at row: " << recordCount + 2 << endl;
                re = false;
            }
            if (validateHelp.IsNumber(T))
            {
                tempLog.SetAirTemp(stof(T));
            }
            else
            {
                cout << "Error: Invalid Ambient Air Temperature(T) detected at row: " << recordCount + 2 << endl;
                re = false;
            }
            // Insert the Weather object into the map
            try
            {
                InsertWeatherToMap(windLog, tempLog);
            }
            catch(const exception& e)
            {
                cerr << e.what() << '\n';
                cout << "Failed to load" << endl;
                re = false;
                break; // Break the loop if an exception is caught
            }
            row.clear();
            recordCount++;
        }
    }
    return re;
}
LoadMultiDataFileCSV()
void Logic::LoadMultiDataFileCSV (ifstream & inputFile, map< int, map< int, map< int, Bst< Weather > > > > & windLog)
Reads the input file line by line for filename pass to LoadDataFileCSV function to read and load data into the wind log.
Parameters
inputFile - Input file with the list of data file name to read and load
windLog - The maps of binary search tree of weather for storing Weather object which will store data from data file. This will be passed to LoadDataFileCSV function to load file by file
Definition at line 19 of file Logic.cpp.
{
    string fileName;
    ifstream dataFile;
    //While there is still a line to read in input file
    while(getline(inputFile,fileName))
    {
        //Check if line is not empty/blank
        if(fileName != "")
        {
            //Open the file using the line
            dataFile.open("data/" + fileName);
            if(dataFile.is_open())
            {
                cout << "Loading file: " + fileName << endl;
                if(LoadDataFileCSV(dataFile,windLog) == false)
                {
                    cout << "Error loading data file: " + fileName << endl;
                }
                else
                {
                    cout << "Loaded data file: " + fileName << endl;
                }
                dataFile.close();
            }
            else
            {
                cout << "Error while opening file: " + fileName << endl;
            }
        }
    }
}
RemoveLeadingZeros()
string Logic::RemoveLeadingZeros (string input)
Removes leading 0 s from a given string.
Parameters
input - The input string
Returns
string - The string after removing leading 0 s
Definition at line 257 of file Logic.cpp.
{
    return input.erase(0, min(input.find_first_not_of('0'), input.size() - 1));
}
StandardDeviationAirTemperature()
float Logic::StandardDeviationAirTemperature (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year)
Calculates the standard deviation of air temperature for a specified month and year.
This method searches the wind log for the specified month and year and calculates the standard deviation of air temperature.
Parameters
windLog - The map of BSTs containing the weather data.
month - The month to search for.
year - The year to search for.
Returns
The standard deviation of air temperature for the specified month and year.
Definition at line 378 of file Logic.cpp.
{
    float totalAirTemperature = 0.0;
    Vector<float> airTemperatures;
    // Check if data of that year exist
    if(windLog.count(year) > 0)
    {
        // Check if data of that year and month exist
        if(windLog.at(year).count(month) > 0)
        {
            // Loop through the month map for each day
            for (const auto& dayEntry : windLog.at(year).at(month))
            {
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                {
                    airTemperatures.push_back(w.GetAirTemperature());
                    return w.GetAirTemperature();
                });
            }
        }
        else
        {
            return -1;
        }
    }
    else
    {
        return -1;
    }
    // Calculate mean
    for (float airTemp : airTemperatures)
    {
        totalAirTemperature += airTemp;
    }
    float mean = totalAirTemperature / airTemperatures.size();
    // Calculate variance
    float variance = 0.0;
    for (float airTemp : airTemperatures)
    {
        variance += pow(airTemp - mean, 2);
    }
    variance /= airTemperatures.size();
    // Calculate standard deviation
    return sqrt(variance);
}
StandardDeviationWindSpeed()
float Logic::StandardDeviationWindSpeed (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year)
Calculates the standard deviation of wind speed for a specified month and year.
This method searches the wind log for the specified month and year and calculates the standard deviation of wind speed.
Parameters
windLog - The map of BSTs containing the weather data.
month - The month to search for.
year - The year to search for.
Returns
The standard deviation of wind speed for the specified month and year.
Definition at line 295 of file Logic.cpp.
{
    float totalWindSpeed = 0.0;
    Vector<float> windSpeeds;
    // Check if data of that year exist
    if(windLog.count(year) > 0)
    {
        // Check if data of that year and month exist
        if(windLog.at(year).count(month) > 0)
        {
            // Loop through the month map for each day
            for (const auto& dayEntry : windLog.at(year).at(month))
            {
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                {
                    windSpeeds.push_back(w.GetWindSpeed());
                    return w.GetWindSpeed();
                });
            }
        }
        else
        {
            return -1;
        }
    }
    else
    {
        return -1;
    }
    // Calculate mean
    for (float windSpeed : windSpeeds)
    {
        totalWindSpeed += windSpeed;
    }
    float mean = totalWindSpeed / windSpeeds.size();
    // Calculate variance
    float variance = 0.0;
    for (float windSpeed : windSpeeds)
    {
        variance += pow(windSpeed - mean, 2);
    }
    variance /= windSpeeds.size();
    // Calculate standard deviation
    return sqrt(variance);
}
SumSolarRadiationMonth()
float Logic::SumSolarRadiationMonth (const map< int, map< int, map< int, Bst< Weather > > > > & windLog, const int month, const int year)
Search and Calculates the total solar radiation of a month when given the month and year to search for.
Parameters
array - The maps of binary search tree of weather to search in
month - The month to search for
year - The year to search for
Returns
float - The total solar radiation of a month
Definition at line 428 of file Logic.cpp.
{
    float totalSolarRadiation = 0.0;
    Vector<float> solarRads;
    // Check if data of that year exist
    if(windLog.count(year) > 0)
    {
        // Check if data of that year and month exist
        if(windLog.at(year).count(month) > 0)
        {
            // Loop through the month map for each day
            for (const auto& dayEntry : windLog.at(year).at(month))
            {
                dayEntry.second.InOrderTraversalFloat([&](Weather& w)
                {
                    // Check if solar radiation is greater than 100 before adding
                    if (w.GetSolarRadiation() > 100)
                    {
                        solarRads.push_back(w.GetSolarRadiation());
                    }
                    return w.GetSolarRadiation();
                });
            }
        }
        else
        {
            return -1;
        }
    }
    else
    {
        return -1;
    }
    for (float solarRad : solarRads)
    {
        totalSolarRadiation += solarRad;
    }
    return totalSolarRadiation;
}
WriteAppendFile()
void Logic::WriteAppendFile (const string & fileName, const string & output)
Create/Appends a given string into "WindTempSolar.csv".
Parameters
output - The string to append
Definition at line 523 of file Logic.cpp.
{
    ofstream OutputFile(fileName, ofstream::app);
    //appends the string and proceed to next line
    OutputFile << output << endl;
    OutputFile.close();
}
The documentation for this class was generated from the following files:
Logic.h
Logic.cpp