WeatherLogSystem2: Time Class Reference
Time Class Reference
#include <Time.h>
Public Member Functions
Time ()
Construct a new Time object.
Time (unsigned int h, unsigned int m)
Construct a new Time object.
~Time ()
Destroy the Time object.
int GetHour () const
Get the Hour object.
int GetMinute () const
Get the Minute object.
void SetHour (const unsigned int h)
Set the Hour object.
void SetMinute (const unsigned int m)
Set the Minute object.
string Display24HTime () const
Display 24 hour.
Private Attributes
int m_hour
int m_minute
Detailed Description
Definition at line 24 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time () inline
Construct a new Time object.
Definition at line 32 of file Time.h.
:m_hour(-1), m_minute(-1) {};
References m_hour, and m_minute.
Time() [2/2]
Time::Time (unsigned int h, unsigned int m)
Construct a new Time object.
Parameters
h hour
m minute
Definition at line 12 of file Time.cpp.
{
    m_hour = h;
    m_minute = m;
}
References m_hour, and m_minute.
Referenced by main().
~Time()
Time::~Time () inline
Destroy the Time object.
Definition at line 46 of file Time.h.
{};
Member Function Documentation
Display24HTime()
string Time::Display24HTime () const
Display 24 hour.
Returns
string
Definition at line 38 of file Time.cpp.
{
    string result;
    if(m_hour < 10)
    {
        result += "0" + to_string(m_hour);
    }
    else
    {
        result += to_string(m_hour);
    }
    result += ":";
    if(m_minute < 10)
    {
        result += "0" + to_string(m_minute);
    }
    else
    {
        result += to_string(m_minute);
    }
    return result;
}
References m_hour, and m_minute.
GetHour()
int Time::GetHour () const
Get the Hour object.
Returns
int
Definition at line 18 of file Time.cpp.
{
    return m_hour;
}
References m_hour.
Referenced by operator<(), operator==(), and operator>().
GetMinute()
int Time::GetMinute () const
Get the Minute object.
Returns
int
Definition at line 23 of file Time.cpp.
{
    return m_minute;
}
References m_minute.
Referenced by operator<(), operator==(), and operator>().
SetHour()
void Time::SetHour (const unsigned int h)
Set the Hour object.
Parameters
h hour
Definition at line 28 of file Time.cpp.
{
    m_hour = h;
}
References m_hour.
Referenced by main().
SetMinute()
void Time::SetMinute (const unsigned int m)
Set the Minute object.
Parameters
m minute
Definition at line 33 of file Time.cpp.
{
    m_minute = m;
}
References m_minute.
Referenced by main().
Member Data Documentation
m_hour
int Time::m_hour private
Definition at line 84 of file Time.h.
Referenced by Display24HTime(), GetHour(), SetHour(), Time(), and Time().
m_minute
int Time::m_minute private
Definition at line 85 of file Time.h.
Referenced by Display24HTime(), GetMinute(), SetMinute(), Time(), and Time().
The documentation for this class was generated from the following files:
Time.h
Time.cpp