var files_dup =
[
    [ "Bst.h", "_bst_8h.html", "_bst_8h" ],
    [ "BstTest.cpp", "_bst_test_8cpp.html", "_bst_test_8cpp" ],
    [ "BstWeatherHelper.cpp", "_bst_weather_helper_8cpp.html", null ],
    [ "BstWeatherHelper.h", "_bst_weather_helper_8h.html", "_bst_weather_helper_8h" ],
    [ "BstWeatherHelperTest.cpp", "_bst_weather_helper_test_8cpp.html", "_bst_weather_helper_test_8cpp" ],
    [ "Date.cpp", "_date_8cpp.html", null ],
    [ "Date.h", "_date_8h.html", "_date_8h" ],
    [ "DateTest.cpp", "_date_test_8cpp.html", "_date_test_8cpp" ],
    [ "FunctionHelper.cpp", "_function_helper_8cpp.html", null ],
    [ "FunctionHelper.h", "_function_helper_8h.html", "_function_helper_8h" ],
    [ "FunctionHelperTest.cpp", "_function_helper_test_8cpp.html", "_function_helper_test_8cpp" ],
    [ "Logic.cpp", "_logic_8cpp.html", null ],
    [ "Logic.h", "_logic_8h.html", "_logic_8h" ],
    [ "LogicTest.cpp", "_logic_test_8cpp.html", "_logic_test_8cpp" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "Time.cpp", "_time_8cpp.html", "_time_8cpp" ],
    [ "Time.h", "_time_8h.html", "_time_8h" ],
    [ "TimeTest.cpp", "_time_test_8cpp.html", "_time_test_8cpp" ],
    [ "Validator.cpp", "_validator_8cpp.html", null ],
    [ "Validator.h", "_validator_8h.html", "_validator_8h" ],
    [ "ValidatorTest.cpp", "_validator_test_8cpp.html", "_validator_test_8cpp" ],
    [ "Vector.h", "_vector_8h.html", "_vector_8h" ],
    [ "VectorTest.cpp", "_vector_test_8cpp.html", "_vector_test_8cpp" ],
    [ "Weather.cpp", "_weather_8cpp.html", "_weather_8cpp" ],
    [ "Weather.h", "_weather_8h.html", "_weather_8h" ],
    [ "WeatherTest.cpp", "_weather_test_8cpp.html", "_weather_test_8cpp" ]
];